Repository IMY772-2022/via-web, pull requests merged in 2022-04, with the labels that each got.

#15 feat: add Predictions libray
  .eslintrc.js
  amplify/backend/auth/viaweb22e998c1/cli-inputs.json
  amplify/backend/backend-config.json
  amplify/backend/predictions/identifyEntities3356fa5f/identifyEntities3356fa5f-template.json
  amplify/backend/predictions/identifyEntities3356fa5f/parameters.json
  amplify/backend/predictions/identifyLabelsb6bf62be/identifyLabelsb6bf62be-template.json
  amplify/backend/predictions/identifyLabelsb6bf62be/parameters.json
  amplify/backend/predictions/speechGenerator10151959/parameters.json
  amplify/backend/predictions/speechGenerator10151959/speechGenerator10151959-template.json
  amplify/backend/types/amplify-dependent-resources-ref.d.ts
  amplify/team-provider-info.json
  package-lock.json
  package.json
  src/aws-exports.d.ts
  src/components/Home/index.tsx
  src/components/Landing/index.tsx
  src/components/PhotoAnalysis/TextToSpeech/index.tsx
  src/components/PhotoAnalysis/index.tsx
  src/pages/index.tsx
  tsconfig.json
  types/aws-exports.d.ts
  yarn.lock
Labels: enhancement

#17 feature: photo analysis page
  .gitignore
  src/components/Button/index.scss
  src/components/Button/index.tsx
  src/components/Landing/index.scss
  src/components/Landing/index.tsx
  src/components/Layout/index.tsx
  src/components/Navigation/index.tsx
  src/components/PhotoAnalysis/TextToSpeech/index.tsx
  src/components/PhotoAnalysis/index.tsx
  src/components/icons/BrandIcon.tsx
  src/images/via-logo.svg
  src/pages/index.tsx
  src/pages/photo-analysis.tsx
  yarn.lock
Labels: enhancement, ui

#18 feature: PWA support
  gatsby-config.ts
  package-lock.json
  package.json
  src/components/Seo/index.tsx
  src/pages/index.tsx
  yarn.lock
Labels: enhancement

#26 chore: remove yarn
  README.md
  package.json
  yarn.lock
Labels: documentation, dependencies
