Repository IMY772-2022/via-web, pull requests merged in 2022-06, with the labels that each got.

#54 feat: new photo and profile ui
  src/components/Landing/Landing.tsx
  src/components/Landing/landing.scss
  src/components/PhotoAnalysis/PhotoAnalysis.tsx
Labels: ui

#69 feat: onboarding ui
  src/components/Navigation/Navigation.tsx
  src/components/Onboarding/Onboarding.tsx
  src/components/Onboarding/onboarding.scss
  src/pages/onboarding.tsx
Labels: ui

#71 ci: fix GitHub build
  .github/workflows/ci.yml
  TEST
  package-lock.json
  yarn.lock
Labels: dependencies

#68 Feature/edit labels
  src/components/Album/Item.tsx
  src/components/Alert/Alert.tsx
  src/components/ConfirmationModal/ConfirmationModal.tsx
  src/components/ConfirmationModal/confirmationMoadal.scss
  src/components/Edit/Edit.tsx
  src/components/Edit/edit.scss
  src/components/Label/Label.tsx
  src/components/Landing/landing.scss
  src/components/PhotoAnalysis/photoAnalysis.scss
  src/components/PhotoAnalysis/utils.tsx
  src/pages/edit.tsx
Labels: enhancement

#72 feat: album ui
  src/components/Album/Album.scss
  src/components/Album/Album.tsx
  src/components/Album/Item.scss
  src/components/Album/Item.tsx
  src/components/Edit/Edit.tsx
  src/components/Edit/edit.scss
  src/components/Layout/Layout.tsx
  src/components/Onboarding/Onboarding.tsx
  src/components/Onboarding/onboarding.scss
  src/pages/album.tsx
  src/styles.scss
Labels: enhancement

#86 Fixing the css on photoanlysis screen
  src/components/Landing/landing.scss
  src/components/PhotoAnalysis/PhotoAnalysis.tsx
  src/components/PhotoAnalysis/photoAnalysis.scss
Labels: ui

#87 feature: auth context
  gatsby-browser.ts
  src/components/Auth/SignIn.tsx
  src/components/Auth/hooks.ts
  src/components/Auth/utils.tsx
  src/components/Landing/Landing.tsx
  src/components/Layout/Layout.tsx
  src/components/Navigation/Navigation.tsx
  src/context/reducer.ts
  src/context/store.tsx
  src/pages/album.tsx
  src/pages/edit.tsx
  src/pages/index.tsx
  src/pages/onboarding.tsx
  src/pages/register.tsx
  src/pages/signin.tsx
  src/pages/signout.tsx
  src/wrapPageElement.tsx
  src/wrapRootElement.tsx
Labels: enhancement

#89 Api feedback
  src/components/Alert/Alert.tsx
  src/components/PhotoAnalysis/PhotoAnalysis.tsx
  src/components/PhotoAnalysis/utils.tsx
Labels: enhancement

#95 Update the routing of the app
  src/components/Auth/Register.tsx
  src/components/Auth/hooks.ts
  src/components/Auth/utils.tsx
  src/components/Edit/edit.scss
  src/components/Navigation/Navigation.tsx
  src/components/Onboarding/Onboarding.tsx
  src/components/Onboarding/onboarding.scss
  src/pages/index.tsx
  src/pages/onboarding.tsx
  src/pages/photo-analysis.tsx
Labels: enhancement, ui

#94 Add api feedback for edit
  src/components/Edit/Edit.tsx
  src/components/PhotoAnalysis/utils.tsx
Labels: enhancement

#98 fix: move QueryClientProvider to root element & added additional prov…
  src/components/Layout/Layout.tsx
  src/pages/edit.tsx
  src/wrapPageElement.tsx
  src/wrapRootElement.tsx
Labels: bug

#99 feat: general ui
  src/components/Album/Album.tsx
  src/components/Album/Item.scss
  src/components/Album/Item.tsx
  src/components/Edit/Edit.tsx
  src/components/Edit/edit.scss
  src/components/Onboarding/Onboarding.tsx
  src/components/Onboarding/onboarding.scss
  src/components/PhotoAnalysis/photoAnalysis.scss
  src/styles.scss
Labels: ui

#106 feature: hide save when not signed in
  src/components/Landing/Landing.tsx
  src/components/PhotoAnalysis/PhotoAnalysis.tsx
  src/components/PhotoAnalysis/photoAnalysis.scss
  src/pages/photo-analysis.tsx
Labels: bug, ui

#117 Add email validation
  src/components/Auth/Register.tsx
Labels: enhancement

#120 fix: general lighthouse issues
  lighthouserc.js
  src/components/Auth/Register.scss
  src/components/Auth/SignIn.scss
  src/components/Edit/edit.scss
  src/components/Navigation/Navigation.tsx
  src/context/ThemeContext/store.tsx
  src/styles.scss
Labels: bug, enhancement, ui
