Repository IMY772-2022/via-web, pull requests merged in 2022-05, with the labels that each got.

#32 chore: update eslit & husky
  .eslintrc.js
  .gitignore
  .husky/pre-commit
  package-lock.json
  package.json
  src/components/Landing/Landing.tsx
Labels: documentation, enhancement, dependencies

#33 style: general styling improvements
  src/components/Button/button.scss
  src/components/Landing/Landing.tsx
  src/components/Landing/landing.scss
  src/components/PhotoAnalysis/PhotoAnalysis.scss
  src/components/PhotoAnalysis/PhotoAnalysis.tsx
  src/components/PhotoAnalysis/TextToSpeech/TextToSpeech.tsx
Labels: ui

#36 Feature: add Cognito with signin/register components
  package-lock.json
  package.json
  src/components/Auth/Register.tsx
  src/components/Auth/SignIn.tsx
  src/components/Auth/utils.tsx
  src/components/Layout/Layout.tsx
  src/components/Navigation/Navigation.tsx
  src/pages/register.tsx
  src/pages/signin.tsx
Labels: enhancement

#40 fix: import & file naming
  src/components/PhotoAnalysis/PhotoAnalysis.scss
Labels: ui

#42 Add error component + auth feedback for signin
  src/components/Alert/Alert.tsx
  src/components/Auth/SignIn.tsx
  src/components/Auth/utils.tsx
Labels: enhancement

#39 ci: add lighthouse ci testing
  .github/workflows/ci.yml
  lighthouserc.js
  src/components/PhotoAnalysis/PhotoAnalysis.tsx
  src/components/PhotoAnalysis/rekognitionUtils.tsx
Labels: enhancement, testing

#43 feat: sign in component ui
  package-lock.json
  package.json
  src/components/Auth/SignIn.scss
  src/components/Auth/SignIn.tsx
  src/components/Layout/Layout.tsx
  src/pages/register.tsx
  src/pages/signin.tsx
Labels: ui

#46 chore: add open sans font
  src/components/Auth/SignIn.scss
  src/styles.scss
  static/fonts/OpenSans/OpenSans-Bold.ttf
  static/fonts/OpenSans/OpenSans-BoldItalic.ttf
  static/fonts/OpenSans/OpenSans-ExtraBold.ttf
  static/fonts/OpenSans/OpenSans-ExtraBoldItalic.ttf
  static/fonts/OpenSans/OpenSans-Italic.ttf
  static/fonts/OpenSans/OpenSans-Light.ttf
  static/fonts/OpenSans/OpenSans-LightItalic.ttf
  static/fonts/OpenSans/OpenSans-Medium.ttf
  static/fonts/OpenSans/OpenSans-MediumItalic.ttf
  static/fonts/OpenSans/OpenSans-Regular.ttf
  static/fonts/OpenSans/OpenSans-SemiBold.ttf
  static/fonts/OpenSans/OpenSans-SemiBoldItalic.ttf
Labels: enhancement

#48 refactor: font paths & references
  gatsby-config.ts
  src/styles.scss
  static/fonts/OpenSans-Bold.ttf
  static/fonts/OpenSans-BoldItalic.ttf
  static/fonts/OpenSans-ExtraBold.ttf
  static/fonts/OpenSans-ExtraBoldItalic.ttf
  static/fonts/OpenSans-Italic.ttf
  static/fonts/OpenSans-Light.ttf
  static/fonts/OpenSans-LightItalic.ttf
  static/fonts/OpenSans-Medium.ttf
  static/fonts/OpenSans-MediumItalic.ttf
  static/fonts/OpenSans-Regular.ttf
  static/fonts/OpenSans-SemiBold.ttf
  static/fonts/OpenSans-SemiBoldItalic.ttf
Labels: bug

#47 Chore(s): fix signin component labels, update register component, ext…
  src/components/Alert/Alert.tsx
  src/components/Auth/Register.tsx
  src/components/Auth/SignIn.tsx
Labels: bug

#57 Register UI
  src/components/Auth/Register.scss
  src/components/Auth/Register.tsx
  src/components/Button/button.scss
  src/components/Landing/Landing.tsx
  src/components/Landing/landing.scss
  src/components/PhotoAnalysis/photoAnalysis.scss
Labels: ui
